### PR TITLE
ENH: add M26 JTAG configuration

### PR DESCRIPTION
**Pull request by thirono**

### CODE REVIEW

**Comment by DavidLP** [comment]
Fine with me. Although cleanup at a certain point would be nice.

**Comment by laborleben** [comment]
Right here would be the right place

**Comment by laborleben** [comment]
1. the pybar/config folder is not used anymore. The folder still exists for historical reasons. I suggest creating a pybar/mimosa26 folder (not m26, use full name).
2. one really need a yaml file for each threshold?
3. the default configuration can be a dictionary which can be loaded the same way as a yaml file. The advantage is, that the dict gives you more flexibility and you can avoid repeating the default conf by importing.
4. Why do you set self.dut['TLU']['TRIGGER_ENABLE'] = True? See also https://github.com/SiLab-Bonn/basil/tree/master/firmware/modules/tlu
5. The filename is not following our convention.

**Comment by laborleben** [comment]
Guy, what worries me, that you all do the fixes and merges so quickly, that there is no discussion about it anymore. With that speed, we are not getting to the optimum solution. Toko was so kind to do a branch, and we should take the opportunity to work on that branch before it gets merges.
If you want to do it quick and dirty, then go on, but without me.

**Comment by themperek** [comment]
Actually this commit does not modify or break anything. The branch is called 'development' but this is philosophy now.
ad 1) Then you should remove this 
ad 2) Suggest better.
ad 3)  ?
ad 4) because it changed few times during TLU development process and it did not work other way at some point (maybe now works)
ad 5) can change

**Comment by laborleben** [comment]
1. we talked about this, mimosa26 inside pybar folder
2. run_conf parameter
3. the yaml files are repeating itself, most of the content is redundant. Use a dict and import and append redundant configuration.

**Comment by laborleben** [comment]
to 4. the current scan enables the trigger, then enables the Mimosa26, and then enables the trigger again. Does not make sense.

**Comment by laborleben** [comment]
I want to do a release very soon (the last release with single chip support). I want to clean up the dev branch, merge from there to master and do the tag. The usual way.
After that you can do what you want.

**Comment by themperek** [comment]
Will manage somehow ;-) 
https://www.entrepreneur.com/article/249676

**Comment by laborleben** [comment]
that is leading into wrong direction, this is meant for startups. I don't need to sell very quickly. And there is no time pressure.

You remember the discussion about the FIFO readout thread? I cannot imagine pyBAR without it...

**Comment by DavidLP** [comment]
I do not see why we should require new features to be well done when they are put into development if they do not lead to regressions and do not change existing files.
So this is a _stand alone_ new feature that needs cosmetic changes. Why not to put it into development?

**Pull request merged**
